#include "request_parser.h"

#include <cassert>
#include <cstdint>
using namespace std;

// "Driver" for fuzz testing. Takes a buffer with data generated by the fuzzer.
extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
  try {
    // Convert buffer to a string.
    string data_str(reinterpret_cast<const char *>(data), size);
    // Parse the string
    Request request(data_str);

    // Can the fuzzer generate a valid HTTP/1.1 request?
    if (request.version_major == 1 && request.version_minor == 1) {
      assert(0 && "Hoorray for fuzz testing!");
    }
  } catch (BadRequest e) {}

  return 0;
}
